# Generated by Django 2.2.15 on 2020-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200812_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
